name: Validate changes

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          yarn install --frozen-lockfile

      - name: Check Typescript
        run: |
          yarn types:check

      - name: Run Tests
        timeout-minutes: 4
        env:
          NODE_ENV: test
          CI: true
        run: |
          yarn test:ci
