name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run Tests
        timeout-minutes: 4
        env:
          NODE_ENV: test
          CI: true
        run: |
          yarn test:ci
